-- Drop existing objects if they exist
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.account CASCADE;
DROP TABLE IF EXISTS public.classification CASCADE;
DROP TYPE IF EXISTS public.account_type CASCADE;

-- Create custom enum type for account roles
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

-- Create Classification Table
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Create Inventory Table
CREATE TABLE public.inventory (
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create Account Table
CREATE TABLE public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Add foreign key constraint
ALTER TABLE public.inventory
ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id) 
REFERENCES public.classification (classification_id) 
MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;

-- Insert Classification Data
INSERT INTO public.classification (classification_name) VALUES
('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');

-- Insert Inventory Data
INSERT INTO public.inventory (
    inv_make, inv_model, inv_year, inv_description, 
    inv_image, inv_thumbnail, inv_price, inv_miles, 
    inv_color, classification_id
) VALUES 
    ('DMC', 'Delorean', '1981', 'The iconic time-traveling vehicle with flux capacitor',
     '/images/delorean.jpg', '/images/delorean-tn.jpg',
     45000, 15000, 'Silver', 1),
     
    ('GM', 'Hummer', '2023', 'small interiors with advanced off-road capabilities',
     '/images/hummer.jpg', '/images/hummer-tn.jpg',
     85000, 5000, 'Black', 3),
     
    ('Ford', 'Mustang', '2024', 'Classic American muscle car with modern performance',
     '/images/mustang.jpg', '/images/mustang-tn.jpg',
     35000, 2000, 'Blue', 2),
     
    ('Chevrolet', 'Camaro', '2023', 'Sporty coupe with powerful engine',
     '/images/camaro.jpg', '/images/camaro-tn.jpg',
     32000, 3000, 'Yellow', 2);

-- TASK 1 - Query 4: Modify GM Hummer description
UPDATE public.inventory 
SET inv_description = REPLACE(
    inv_description, 
    'small interiors', 
    'a huge interior'
) 
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- TASK 1 - Query 6: Update image paths to include /vehicles
UPDATE public.inventory 
SET 
    inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
